version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "p@ss0wrd!"
        ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    expose:
      - 1433

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 80:80

